language: node_js
sudo: false
node_js:
- '6'

script:
  - npm run build
  - ./node_modules/.bin/karma start --single-run --browsers Firefox --reporters mocha
  
  - npm run build_npm
  
  - node tools/run-typings-test.js
  
  
